# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48a0bed04c20a1219b4da3298908e2c771686fcf73dc8986125ca4f07383a5740a5acc07b32953c57cb59b9e63e17b4a3ac2427e4ef5dc08027b8db8ca2c1790

test:
  secret_key_base: 98d122439c95d7a64990caa240fafc4abc9e85fea2d244a90a933654cb5cfde323a3d7e83240dbd60e8d178fe44485c5d38b8275d55931afce0d858d3ee4cfe8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
